module.exports = ["Good evening.",
"Welcome to the show.",
"The extra buttons.",
"Yeah.",
"What kind of a sicko, really, would save these have them in a huge file? Drawers that wide.",
"You know, you just.",
"Where the hell is that but I mean, is it that hard to get black, round buttons that they make it into a whole thing? Like this is such a great jacket.",
"These buttons are so unique, so oneofakind.",
"You'll never find them.",
"We'll save you the trouble of knocking your brains out.",
"We know they're going to fall off too.",
"That's the other point that they're trying to make here.",
"Everyone in my family's creative.",
"And even though I'm working as an accountant right now I'd really like to eventually work exclusively on my papiermâché hats.",
"I don't understand.",
"Papiermâché hats? What if it rains? They're art.",
"You hang them on the wall.",
"Art.",
"It's my creative outlet, one of my passions.",
"Any money in it? Who so belongs only to his age reverences only its popinjays and mumbo jumbos.",
" Of course.",
"Right.",
"Thomas Carlyle, 1 864.",
"Tommy C.",
"These are the receipts from '85.",
"And I'm gonna do '86.",
"I'm sorry.",
"I thought it was a legitimate charity.",
"I didn't know you'd get audited.",
"I don't blame you.",
"I blame myself.",
"No, blame me.",
"Okay, I blame you.",
"No, no, don't blame me.",
"What was I supposed to do? I was on my first date with Elaine.",
"You come barging in here, asking me to contribute money to a volcano relief fund for Krakatoa.",
"It was supposed to erupt.",
"I find the whole thing embarrassing.",
"Well, you know what my feelings are about this.",
"I don't even pay taxes.",
"Yeah.",
"That's easy when you have no income.",
"Hi.",
"Hi.",
"Kramer, do me a favor, will you? lf you insist on making pasta in my apartment please don't put the tomato sauce on the pasta while it's in the strainer.",
"All the little squares have hardened red sauce in them.",
"What's so funny? Oh, I don't know.",
"Kramer dating your roommate, it's funny.",
"It's a riot, Alice.",
"When do you put the sauce on? Any other time.",
"No, no, no.",
"I like to strain the sauce.",
"And I could really live without the tribal music and the makeout sessions in the living room.",
"Yeah, Tina likes the couch.",
"What are you doing? What is all this? Oh, he's helping me sort my receipts.",
"I'm being audited.",
"You're being audited? What for? Oh, I contributed money to a charity that turned out to be fraudulent.",
"It's really very boring.",
"When was this? A long, long time ago in a galaxy far, far away.",
"I remember you donated to some volcano thing on our first date.",
"Volcano? Really? Oh, wait a minute.",
"Don't tell me that that was Something to drink? What, did you think that would impress me? You've got me all wrong.",
"I was thinking only of the poor Krakatoan.",
"Like you'd make this donation for 50 bucks and I'd start tearing my clothes off? Those brave Krakatoans east of Java who sacrificed so much, for so long.",
"Now you're being audited because of it.",
"See, that's karma.",
"No, that's Kramer.",
"So, what are you gonna do? It's all taken care of.",
"How is that? An old friend of mine, whom you may have met George Costanza, has recently become intimate with a female accountant who was formerly a highly placed official with a little outfit known as the IRS.",
"And as we speak, at this very moment he is handing over to her all of my pertinent tax information and she has assured us that the matter is well within her field of expertise.",
"Why is she doing this? I don't know.",
"It must be love.",
"I don't think we should see each other anymore.",
"You're great but I'm riddled with personal problems.",
"What's wrong? What did I do? Nothing.",
"It's not you.",
"It's me.",
"I have a fear of commitment.",
"I don't know how to love.",
"You hate my earrings, don't you? No, no.",
"And you didn't comment on the chopsticks.",
"I love the chopsticks.",
"I personally prefer a fork, but they look very nice.",
"You're not telling me the truth.",
"I must have done something.",
"I have a fear of intimacy.",
"l Don't give me clichés.",
"I have a right to know.",
"What did I do? Nothing.",
"It's not you.",
"I want the truth! The truth? You want the truth?! It is your earrings! It is your chopsticks.",
"But it's so much more.",
"You're pretentious.",
"You call everyone by their full name.",
"You called my doorman Sammy, Samuel.",
" But you didn't even say Samuel.",
"You went Samuel.",
" Papiermâché? What is papiermâché? Keep going.",
"I think I made my point.",
"I'm sorry if I was a little harsh.",
"No.",
"I asked for the truth.",
"Thank you for being so honest.",
"Can l? Can I walk you back to work? I really prefer to go alone.",
"How much do I owe? Oh, please.",
"Four dollars is fine.",
"lf this audit had happened to me and I didn't have this woman to help me I would've killed this man.",
"I would've strangled him with my bare hands.",
"I don't blame you.",
"Ever been through an audit? No.",
"It's hell.",
"It's the financial equivalent of a complete rectal examination.",
"I would've killed this man.",
"Torn him limb from limb.",
"Ripped the flesh right off his bones.",
"Yeah? It's George.",
"Come on up.",
"There he is, the man himself George Louis Costanza.",
"Here I am, about to go to the electric chair and my oldest friend is dating the governor.",
"My whole life has been a complete waste of time.",
"And there's so much more to go.",
"Now I know what I'm supposed to do.",
"It is so simple.",
"Tell the truth.",
"That's all.",
"Just tell the truth.",
"You give her my tax papers? What? My papers? What? Oh, the papers.",
"You didn't give her the papers? No, I did.",
"So? I broke up with her.",
"You what? I broke up with her.",
"I'm being audited and you broke up with her? It's okay.",
"It's fine.",
"She'll do it.",
"I'm sure she'll still do it.",
"Why? Why will she still do it? She hates you now.",
"People don't do you favors after you dump them.",
"No, no.",
"We left on good terms.",
"How is that possible? Because l I told her the truth.",
"Oh, my God.",
"Okay.",
"It's unheard of.",
"She asked me to.",
"So you lie.",
"What did you tell her? I told her that she was pretentious.",
"Pretentious? The woman has my tax papers.",
"You told her she's pretentious? The IRS they're like the Mafia.",
"They take anything they want.",
"How would you like it if someone told you the truth? What? What could they say? There are plenty of things to say.",
"Like what? I'm bald? What is it specifically? Is there an odor I'm not aware of? George, please.",
"Give me one.",
"You sure? Yes.",
"Okay.",
"You're extremely careful with money.",
"I'm what? Forget it.",
"I'm cheap? You think I'm cheap?! How could you say that to me? I can't believe this! How could you say that to me? You asked me to.",
"You should've lied.",
"So should you! Okay, wait a second.",
"What happened to my papers? I'm not really working right now.",
"I know.",
"When I was working, I spent, baby! Yeah, I know.",
"Champagne, limos, cigars.",
"What happened to the papers? She put them in her pocketbook.",
"I guess she took them.",
"A pocketbook or a handbag? Is that relevant? She took them.",
"Call her office.",
"Give me the phone.",
"Yeah, hi, I'd like to speak to Patrice.",
"What? Oh, really.",
"Oh, okay.",
"Thank you.",
"What? What? She never came back from lunch.",
"This is no good.",
"This is no good.",
"Call her house.",
"Hi.",
"Are you okay? No, no.",
"No She hung up.",
"Not good.",
"All right, look, there's nothing to be worried about.",
"She's just a little annoyed right now.",
"Tomorrow, I'll personally go over there.",
"I'll apologize.",
"I'll get the papers.",
"Don't worry.",
"Don't worry.",
"Not good.",
"Yeah, it's a windshield.",
"I can see that.",
"What's it for? I found it on the road.",
"Yeah? I just finished working out.",
"Are you busy? No.",
"Come on up.",
"Can you believe somebody threw this out? I'm gonna make a coffee table out of this and surprise Tina.",
"Well, wouldn't it be invisible? I mean, what, are you gonna just sense it's in front of the couch? Well.",
"Hello.",
"Hello.",
"What's with you two? You haven't told him? Told me what? Go ahead, tell him.",
"I saw her naked.",
"He saw me naked.",
"Kramer saw me naked.",
"Well, it was an accident.",
"Who walks into a woman's bedroom without knocking? I wanna know.",
"I thought it was a closet.",
"Completely naked? Completely naked.",
"Jerry, how can I go on? All right, if it's gonna make you feel any better, you can see me naked.",
"No, thank you.",
"No, I want you to see me naked.",
"No, no, no.",
"I wanna show you.",
"No! Jerry! Hold it.",
"Just a second.",
"Let's not lose our heads here.",
"Kramer, you know you're always welcome in my home but as far as Mr.",
"Johnson is concerned that's another story.",
"What is this? It's a windshield.",
"It's going to be your new coffee table.",
"I'm gonna kill myself on that thing.",
"You can't even see it.",
"You'll sense it.",
"Well? What happened? Was she there? No.",
"No, she wasn't.",
"You didn't get my papers? No, I didn't.",
"Well, where is she? A mental institution.",
"Why is it so difficult, uncomfortable to be naked? It's because we have clothes on you can always make those little adjustments, which people love to do.",
"You feel like you're getting it together.",
"Yeah, I look pretty good.",
"Feeling good, looking good.",
" But when you're naked, it's like It's so final.",
"You're just, Well that's it.",
"There's nothing else I can do.",
" That's why I like to wear a belt when I'm naked.",
"Because I feel it gives me something.",
"Some, you know, I'm naked, but, you know.",
" I'd like to get pockets to hang off of the belt.",
"That would be Wouldn't that be the ultimate thing? To be naked and still be able to do this.",
"I think that would really help a lot.",
"A mental institution? You know what they do in there? Did you see Cuckoo's Nest? They put those electrodes in your head.",
"It's not really a mental institution.",
"It's more like a depression clinic.",
"She went out to Woodhaven and checked herself in.",
"I'm sick over this.",
"Who told you this? Her roommate.",
"I've driven women to lesbianism before but never to a mental institution.",
"My friend Bob Sacamano had shock treatments.",
"But his synapses were so large, had no effect.",
"You know, I hate to raise a crass financial concern but was there any information as to the whereabouts of my papers? She put them in her pocketbook.",
"She probably took them out there with her.",
"So, what now? I don't know.",
"Can we go out there? Where? Woodhaven.",
"We could.",
"I'm very nervous about this.",
"I've never spoken to a mental patient before.",
"My cousin Douglas was in a place like this one time.",
"Came over to my house for dinner, there was no soda and he went berserk.",
"He was screaming, Where's the Pepsi? Where's the Pepsi? I should be in a place like this.",
"I envy this woman.",
"Get to wear slippers all day.",
"Friends visit, they pity you.",
"Pity's very underrated.",
"I like it.",
"It's good.",
"Plus, they give you those word association tests.",
"I love those.",
"They're great.",
"There's no wrong answer.",
"Potato.",
"Tuberculosis.",
"Blanket.",
"Leroy.",
"Grass.",
"Tuberculosis.",
"Oh, boy.",
"Here she comes.",
"Oh, my God.",
"Oh, Kram.",
"Kramer! Kramer, could you please put something on? Well.",
"Oh, boy.",
"Listen, you want some leftovers? I made some African food.",
"There's yambalas and sambusa.",
"Sweetie.",
"Are you coming back to bed? Yeah, yeah.",
"I'll be right there, babe.",
"Hi, Elaine.",
"What did you think of the coffee table? It's invisible.",
"So is everything cool or what? Yeah, you seem a little bit dysfunctional.",
"Well.",
"Come on, Elaine just tell us the truth.",
"The truth? You want the truth? Who are you? This is my friend Jerry.",
"Why are you talking like that? And what do you want? Want? What could I possibly want? I just came because I heard so many nice things about you from George.",
"Gorge thinks I'm pretentious.",
"Pretentious.",
"Who isn't pretentious? I mean if everyone that was pretentious was in a mental institution Obviously, this isn't a mental institution.",
"You're trying to take it back because you're feeling guilty I'm in here.",
"No, that's not it at all.",
"Don't lie, George! I'm not a liar.",
"We're cool.",
"Everything's cool.",
"No problem.",
"We're good.",
"Just chatting.",
"Very friendly.",
"Alrighty.",
"No reason for us to raise our voices.",
"I know what you said.",
"You can't change that.",
"What I said.",
"I say stupid things all the time.",
"I can't go two minutes without saying something dumb.",
"It's one stupid thing after another.",
"So let me ask you, when you come to one of these places do you bring your pocketbook? You should be the one criticizing me.",
"I'm lucky to even know someone like you.",
"Do you mean that? Of course.",
"I'm incapable of guile.",
"He's never guiled.",
"You know, some women keep a lot of important papers in their pocketbooks.",
"Like, for example someone else's personal financial papers.",
"Papers.",
"Oh, Jerry.",
"You're the Jerome with the tax problem.",
"You know, after that date with George I got so cuckoo, I threw out all your papers.",
"So I'd love to help you, but I'll just need the copies.",
"There are no copies.",
"So are you saying you want to continue seeing me? Who makes copies? The truth is I think you make a very nice couple.",
"Oh, Kramer.",
"Here, Kramer? No, no.",
"Let's go to the couch.",
"Yes, I'm trying to get a copy of a receipt for a computer that I bought there.",
"It was 1 98 7.",
"I remember I talked to a guy, had, like, a maroon sport jacket and he might have had a toupee.",
"Oh, it was a weave? Okay, well, then I'll come by.",
"Okay, bye.",
"Anybody want to take a walk down to 48th Street? I think I may have tracked down another receipt.",
"I can't.",
"I got to go visit Tina in the hospital.",
"George? I'm going to a poetry reading with Patrice.",
"Firsttime poets.",
"It's in a burntout building down by the docks.",
"It's supposed to be good.",
"Are you going to the hospital now? Yeah, I suppose I am.",
"All right.",
"Great, great.",
"We'll share a cab.",
"You going by 48th.",
"You can give me a ride.",
"I'm getting in on that.",
"Yeah.",
"You know you're chipping in.",
"You're going that way anyway! Come on.",
"I was audited last year.",
"I have been through an audit.",
"At first, I thought, Well, IRS kind of sounds like Toys 'R' Us.",
"Maybe it won't be so bad.",
"Maybe they have a sense of fun about it.",
"You know? But it's bad.",
"It's an ordeal.",
"And they don't do anything to keep your spirits up through the ordeal.",
"I think they should take all your receipts and put them in one of those big, Lucite sweepstake drums and just kind of crank it around there.",
"Give you a feeling like you might win something.",
"You know what I mean? Then they can pull them out and go: Oh, I'm sorry.",
"That's another illegal deduction but we do have some lovely parting gifts for you.",
"Jail."]