module.exports = ["So I'm on the plane.",
"We left late.",
"Pilot says, We're going to be making up some time.",
"Isn't that interesting? They just make up time.",
"That's why you have to reset your watch.",
"Of course when they say they're making up time obviously, they're increasing the speed of the aircraft.",
"Now my question is, if you can go faster why don't you just go as fast as you can all the time? Come on.",
"There's no cops up here.",
"Nail it.",
"Give it some gas.",
"We're flying.",
"Traveling, of course, is the best education.",
"You know, last year I was ill for 40, 45 countries and I would've gone to more, but I'd just got a puppy.",
"And he was too young to take with me.",
"But not now.",
"I won't travel without him.",
"Is he on the plane now? Oh, yes.",
"Yes, he's in the baggage compartment.",
"I don't know why they won't let him sit up here with me.",
"He's a lot better behaved than most of the dregs you find onboard here.",
"You have any pets? Just my nextdoor neighbor.",
"Well you are missing out on a relationship that could enrich your life in ways that you never even thought possible.",
"How about picking up their? You know.",
"You find that enriching? What's the matter? Oh, I'm feeling a bit queasy.",
"Sir, we're gonna make an emergency landing in Chicago and get you to a hospital.",
"My dog.",
"What about my dog? You have a dog? Do you know anyone on the plane, Mr.",
"Palone? Jerry.",
"How you feeling? Would you take care of Farfel? Farfel? It's his dog.",
"We're landing in Chicago to get him to a hospital.",
"Could you take his dog to New York? The dog? The dog? I'm sure it's only for a day or two.",
"But, you know What if, you know? Give me your address and phone number.",
"I'll call you.",
"The dog? Let go, Farfel.",
"Let go.",
"Give me that.",
"Give me that sneaker, you stupid idiot.",
"Shut up! So, what would you do? It's only been three days.",
"I'm sure he's gonna call.",
"Stop it! Shut up! Do you believe this? Do you believe what I'm dealing with? I got a wild animal in the house.",
"He'd deranged.",
"Maybe he's got rabies.",
"I can get lockjaw.",
"lf only.",
"Look at this place.",
"He's going everywhere.",
"I can't go out of the house at night.",
"I haven't performed in three days.",
"This will be my first night out since I got back.",
"Hey, when you walk him, do you? Do I what? Do you pick it up? Yes, I pick it up.",
"You pick it up? Well, you have to.",
"Oh, boy, would I love to see that.",
"Shut up! Shut up, Farfel! Stop it! I don't know what to do.",
"What if I take it to the pound, then the guy shows up? You should call the airline.",
"They might know where he is.",
"No, I tried.",
"They don't know anything.",
"You gotta put the syrup in first.",
"No, milk.",
"I'm telling you.",
"The guy's a drunk.",
"He's probably on a bender.",
"What is a bender anyhow? I don't know.",
"They drink and they bend things at the bar.",
"I don't know.",
"I can't believe he hasn't called.",
"Two hundred seats on a plane I gotta wind up next to Yukon Jack and his dog Cujo.",
"Shut up! One more day, and you are poundbound! Hey, I'm sorry.",
"I can't watch the dog tonight.",
"Why? We're going to the movies.",
"We're gonna see Prognosis Negative.",
"I can't.",
"I gotta get this Ellen out of my life.",
"You're breaking up? Oh, yeah.",
"The sooner the better.",
"I can't wait to do it.",
"You know some people you worry about whether or not you're gonna hurt their feelings? With her, I'm looking forward to it.",
"Boy, I'd like to get it on video.",
"Watch it in slow motion and freezeframe it.",
"Kramer, I don't know how you lasted as long as you did.",
"You didn't like her? lf you could see her personality it'd be like one of the Elephant Man exhibits where they pull off the sheet and everyone gasps.",
"I can't believe someone hasn't killed her yet.",
"How come you never said anything? You can't tell someone how you feel about their girlfriend till after they stop I tell you.",
"You.",
"I'm talking about people.",
"Are we still going to the movies tonight? No, I can't.",
"I gotta watch Farfel.",
"You and George can go without me.",
"Just me and George? Sure.",
"But we need you.",
"What do you need me for? Because.",
"Yeah? Prognosis Negative.",
"Because I relate to George through you.",
"We're more like friendsinlaw.",
"Besides, we said we'd see Prognosis Negative together.",
"Can't you put some newspapers down or something? No, I can't trust him.",
"He gets insane.",
"I won't enjoy myself.",
"That's right, Farfel, I'm talking about you! Just me and George alone? Let's go, people.",
"Let's go.",
"It's Prognosis Negative time.",
"I can't go.",
"You can't go? Why not? Because I have to watch idiot Farfel.",
"I thought Kramer was watching him.",
"He's breaking up with his girlfriend.",
"What's the problem? Just put newspaper down.",
"No, I don't want that smell in the house.",
"You spritz a little Lysol on it No.",
"It's like BO and cologne.",
"They combine forces into some kind of strange mutant funk.",
"So we're not going? Nah.",
"You two go.",
"You still wanna go? Do you? lf you want.",
"It's It's up to you.",
"Go ahead.",
"Well, I really wanted to see Prognosis Negative with Jerry.",
"You wanna see Ponce de Leon? Ponce de Leon? Okay.",
"You sure you don't wanna go? I want to, but I can't.",
"Oh! I tell you what.",
"How about if I come back here first and I clean everything up? And I open up the windows, and if you're still not satisfied we switch apartments for the night.",
"No.",
"What about this? Forget it.",
"Go ahead.",
"You'll have a good time.",
"I know.",
"It's not that.",
"I just want you to go.",
"Well, thank you very much.",
"I'm telling you, one more day, stink breath! On my block, a lot of people walk their dogs and I always see them walking along with their little poop bags which to me is just the lowest function of human life.",
"lf aliens are watching this through telescopes they're gonna think the dogs are the leaders.",
"lf you see two life forms, one of them is making a poop the other one's carrying it for him.",
"Who would you assume is in charge? So how long did you live there? About three years.",
"That's pretty long.",
"It's not that long, really.",
"Yeah.",
"Do you? So And then you came here.",
"Yeah.",
"So I've been here about six years.",
"'86, '87, '88, '89, '90 '91 .",
"Yep.",
"Bad dog.",
"Bad dog! You go outside! Outside! What do you want from me? Tell me.",
"Money? You want money? I'll give you money.",
"How much? I must have been out of my mind.",
"Look at you.",
"Why don't you do something with your life? You sit around here all day.",
"You contribute nothing to society! You're just taking up space! I mean, how can I be with someone like you? Wouldn't respect myself.",
"I like herbal tea.",
"Chamomile's good.",
"Lemon Lift.",
"Almond Pleasure.",
"Jerry likes Morning Thunder.",
"Jerry drinks Morning Thunder? Yeah.",
"Morning Thunder has caffeine in it.",
"Jerry doesn't drink caffeine.",
"Jerry doesn't know Morning Thunder has caffeine in it.",
"You don't tell him? No.",
"And you should see him.",
"Man, he gets all hyper.",
"He doesn't even know why.",
"He loves it.",
"He walks around going, God, I feel great! You don't tell him? No.",
"That is so funny.",
"I know.",
"Have you ever seen him throw up? Please! Please! I take it all back! Everything.",
"I take it all back! Every word! I love you! I love you! I can't live without you! I'll do anything! That's right.",
"Gavin Palone.",
"What? You're sure? He was released on Monday? Last Monday? Did he leave a phone number or address? Unbelievable.",
"Well, thank you.",
"Thanks.",
"Thanks very much.",
"That's it, Farfel.",
"Party's over.",
"Start packing up your little squeeze toys, buddy boy.",
"You're checking out.",
"It was weird because George and I get along so great in so many situations but this was the first time we went oneonone.",
"Oneonone's a whole different game.",
"Can't pass off.",
"The only time it wasn't uncomfortable was when we were making fun of you.",
"Hello.",
"Boy George, about time.",
"Beautiful.",
"How soon? Okay, here's the plan: We take the dog to the pound, we go right to the movies.",
"Right.",
"You, me and Elaine.",
"Yes, all three of us.",
"I am going.",
"Okay, see you in five minutes.",
"What? Do you have to? What am I supposed to do? I don't want to do it.",
"I like dogs.",
"I'm not sure this is a dog.",
"You know the guy might have just lost your number.",
"I'm in the book, and I have a machine.",
"Jerry, do you know what they do to dogs at the pound? They keep them there for a week.",
"lf nobody claims them, they kill them.",
"Really? How late are they open? What? What is it? I went back with Ellen.",
"That's great.",
"Great.",
"Terrific.",
"Yeah.",
"I really think you guys are good together.",
"Yes.",
"She understands you, and she is not demanding.",
"Do you think that I forgot what you two said about her? We're just trying to be supportive.",
"Yes.",
"We knew you were upset From now on when we pass each other, I don't know you, you don't know me.",
"Oh, Kramer.",
"We didn't mean it.",
"What are you doing? I'm getting my pot.",
"Kramer, we like her.",
"Kramer.",
"What did we say that was so bad? I believe I referred to her personality as a potential science exhibit.",
"I said, How come no one's killed her? Well.",
"Well.",
"Probably shouldn't have said anything.",
"I mean, everybody knows the first breakup never takes.",
"Yeah? Prognosis Negative.",
"Great.",
"Okay, Farfel, put your shoes on.",
"Jerry, can't you just give it one more day? It's not his fault.",
"It's not my dog.",
"I don't know where this booze hound is.",
"All right, I tell you what.",
"How about if you and George go to the movies and I stay here and watch the dog? I can't let you do that.",
"What about Prognosis Negative? We'll see it Sunday.",
"Tonight's the night, right? Prognosis Negative.",
"I'm not going.",
"I'm gonna watch the dog.",
"What does this mean? Well we'll go see something else tonight.",
"We'll see Ponce de Leon.",
"What is with this dog? I thought we were taking it to the pound.",
"She talked me into one more day.",
"Talk.",
"I'm going to the bathroom.",
"Jerry, how long are you gonna be in there? I don't know, regular human time.",
"Why don't you wait and go at the movies? Why shouldn't I go here? Well, you know.",
"Sometimes it's good to get there and make sure you get seats and then go to the bathroom.",
"And isn't it more fun using the urinal? Yeah.",
"Oh, yeah, George.",
"Urinals are fun.",
"Can I go? Hey, go.",
"Who's stopping you? What, are you doing me a favor? Like we care if you go to the bathroom.",
"How's it going? Good.",
"You? Things are good.",
"Boy, he takes such a long time.",
"I know.",
"You know what he does in there? He gargles.",
"Jerry gargles? That why he takes so long? Yeah, he does it like six times a day.",
"How come we never hear him? Because he does it quiet.",
"He does it quiet.",
"Lookit Just like this.",
"Watch.",
"Wait, wait.",
"Did you ever see him throw up? We talked about that already.",
"I have nothing to say to anybody anymore.",
"I'm so uninteresting.",
"I'm think I'm out of conversation.",
"So why do you call me six times a day? All I know about is sports.",
"That's it.",
"No matter how depressed, I can always read sports.",
"I could read the sports section if my hair was on fire.",
"You know what, Ponce de Leon is sold out.",
"It is.",
"Oh, yeah, you're right.",
"What else is playing? Nothing except Prognosis Negative.",
"Boy, I know she really wants to see that with me.",
"Give me that jacket, mud face.",
"This is not Seinfeld you're dealing with.",
"When I get through with you, you'll be begging to go to the pound.",
"Shut up.",
"Shut up! Hello? No.",
"Who's calling? Oh, my God.",
"The dog guy.",
"Well, where have you been? Yeah? Well, you better pick up your dog tonight or he has humped his last leg.",
"I could understand if there was something else playing but it's this or nothing.",
"I don't know what to do.",
"What is this saving movies thing? Something's playing, you go.",
"I know.",
"I know.",
"So we're gonna do nothing now? This is crazy.",
"It is kind of silly.",
"Of course it is.",
"I mean, it's just a movie Exactly.",
"It's not like she's in the movie.",
"Right.",
"We're supposed to ruin the night because she wants to see it? lf I could have seen it with her, fine.",
"But I can't control these circumstances and schedules and people's availabilities.",
"She'll still see it.",
"You're not stopping her How does sitting next to a person in a movie theater increase the enjoyment? You can't talk during a movie.",
"This is stupid.",
"Come on.",
"Let's just go.",
"Good.",
"Saving movies.",
"Ridiculous.",
"Two for Prognosis Negative.",
"I'm in big trouble.",
"Oh, you're dead.",
"Bell's Palsy.",
"The entire side of Of my face was paralyzed.",
"Farfel.",
"You know, I couldn't I couldn't I couldn't even feed myself.",
"I was completely incapacitated.",
"Quiet, Farfel! Farfel.",
"It's interesting because I called the hospital and they said you were released on Monday.",
"Yes, that's true but then, see, I was taken to the Bell's Palsy Center.",
"In In Rockville.",
"Absolutely first Firstrate facility.",
"Top Topnotch physicians.",
"Hey, come on.",
"Come on.",
"Get off me.",
"He won't hurt you.",
"He's just playing.",
"Now you keep that mutt away from me.",
"Mutt? I'll wager his parents are more pure than yours.",
"Kramer, are you coming? Oh, hi, Ellen.",
"Get in here.",
"Listen, it's been a pleasure taking care of your dog for a week but if you don't mind.",
"Prediction: You'll be calling me to ask if you can come and visit him before the month is out.",
"Prediction: I never see you or him again for the rest of my life.",
"We made plans.",
"Why don't we just rent a movie? I thought you wanted to see Prognosis Negative.",
"No.",
"It's supposed to be really bad.",
"Really bad.",
"I mean, it's long.",
"There's no story.",
"It's so unbelievably boring I heard.",
"l.",
"Jerry, you promised me we'd go.",
"Well, George told me the whole story, line for line.",
"I almost feel like I've seen it already and walked out on it.",
"Wait.",
"George saw the movie? I saw him yesterday.",
"He didn't mention it.",
"You and George got together? Yeah.",
"I wanted to talk about how we had nothing to talk about.",
"Hello.",
"Hi, hi, hi.",
"Well, you were right.",
"About what? Ellen.",
"We broke up again.",
"Too bad.",
"I thought she was the one.",
"I'll bring back the pot.",
"Okay, come on.",
"It's movie time.",
"Hey, what are you gonna see? Prognosis Negative.",
"That's supposed to be great.",
"It's not.",
"Well, how do you know? I have an instinct for these things.",
"I had a parakeet when I was a kid.",
"That was the only pet I really enjoyed.",
"We used to let him out of his cage and he would fly around.",
"And my mother had built One entire wall of our living room was mirrored she felt this gives you a feeling of space.",
"Have you ever heard this interiordesign principle? The mirror makes it seem like you have another room.",
"Who walks up to a mirror and goes: Hey, look.",
"There's a whole other room in there.",
"There's a guy in there, looks just like me? But the parakeet will fall for this.",
"You let him out.",
"He flies around.",
"Bang! With his little head.",
"He would just go: I'd always think, even if he thinks the mirror is another room why doesn't he at least try and avoid hitting the other parakeet?"]