module.exports = ["Does it seem to you that the ventriloquist dummy has a very active sexual, social life? He's always talking about dates and women that he knows and bringing them back to the suitcase at night.",
"There's always a sawdust joke in there somewhere, you know.",
"He says kinky things, because he's made out of wood and he can spin his head around.",
"We're somehow expected to believe because the face is so animated they think we're not noticing the feet are just swinging there.",
"Dummy feet never look really right, do they? They're just kind of dangling there.",
"Always kind of askew, you know.",
"You always see a little ankle.",
"Those little thin, fabric ankles that they have, you know.",
"You think, I don't think this thing is real.",
" Are you kidding me? Let me speak with the head librarian.",
"It's absurd.",
"An overdue book from 1 9 7 1 ? This is a joke, right? What are you, from a radio station? Okay, you got me.",
"I fell for it.",
"All right.",
"Okay.",
"I can be down there in, like, a halfhour.",
"Bye.",
"What's the problem? This, you're not gonna believe.",
"The New York Public Library says that I took out Tropic of Cancer in 1 9 7 1 and never returned it.",
"Do you know how much that comes to? That's a nickel a day for 20 years.",
"It's gonna be $50,000.",
"It doesn't work like that.",
"lf it's a dime a day, it could be 1 00,000.",
"It's not gonna be anything.",
"I returned the book.",
"I remember it very vividly because I was with Sherry Becker.",
"She wore this orange dress.",
"It's the first time I saw her in a dress like that.",
"I'd known her since ninth grade.",
"She was developing this body in secret under these loose clothes for, like, two years.",
"And then one day this orange dress.",
"It's burned in my memory.",
"Oh, memory burn, huh? I wonder whatever happened to her.",
"How did they find you? Oh, computers.",
"They're cracking down now on overdue books.",
"The whole thing's completely ridiculous.",
"It's George.",
"Wait till he finds out we're going to the library.",
"He'll be thrilled.",
"You know, I never got a library card.",
"I'm coming down.",
"It's all a bunch of cheapskates in there anyway.",
"People sitting around reading the newspaper attached to those huge wooden sticks trying to save a quarter.",
"Look, I gotta go to the library.",
"You wanna go? Yeah, yeah.",
"Let's go.",
"The Dewey Decimal System.",
"What a scam that was.",
"Boy, this Dewey guy really cleaned up on that deal.",
"Where's George? Look.",
"Trying to save a quarter.",
"I kind of like those sticks.",
"I'd like to get them in my house.",
"This woman's completely ignoring me.",
"Look at her.",
"This is a lonely woman looking for companionship.",
"A spinster.",
"Maybe a virgin.",
"Maybe she got hurt a long time ago.",
"She's a schoolgirl there was a boy.",
"It didn't work out.",
"So now she needs a little tenderness.",
"She needs a little understanding.",
"Needs a little Kramer, huh? Then she'll need a little shot of penicillin.",
"Yes? Yeah, I called before.",
"I got this notice in the mail.",
"Tropic of Cancer.",
"Henry Miller.",
"This case has been turned over to our investigations officer, Mr.",
"Bookman.",
"Bookman? The library investigator's name is actually Bookman? Come on.",
"It's true.",
"That's amazing.",
"That's like an icecream man named Cone.",
"Well, Lieutenant Bookman's been working here 25 years so he's heard all the jokes.",
"Can I speak with this Bookman? Just a second.",
"Jerry.",
"What? I think I saw him.",
"I think it's him.",
"Who? Did you see the homeless guy on the library steps screaming obscenities and doing calisthenics? Yeah.",
"I think that's Mr.",
"Heyman.",
"The gym teacher from our high school.",
"Heyman? Are you sure? He's older completely covered in filth, no whistle.",
"But I think it's him.",
"George got him fired.",
"He squealed on him.",
"Oh, tattletale.",
"I didn't tattle.",
"Well, what did this guy do? What happened? There was an incident.",
"I'd rather not discuss it.",
"Oh, come on.",
"You can tell me.",
"Some other time.",
"What, tonight? I never figured you for a squealer.",
"He sang like a canary.",
"Mr.",
"Bookman's not here.",
"Not here? Why was I told to come down here? He'll be out all afternoon on a case.",
"He's out on a case? He actually goes out on cases? What am I supposed to do now? I'll have Mr.",
"Bookman get in touch with you.",
"All right.",
"Thanks.",
"Come on, let's go.",
"Let's go see if it's Heyman.",
"It's not him.",
"Hey, I'll see you boys later, huh? So, what's a guy gotta do around here to get a library card? Where's Karen? She went to pick up lunch.",
"Well she didn't ask me what I wanted.",
"She must've forgot.",
"How could she forget? I've been ordering lunch every day for threeandahalf years.",
"Is there something you're not telling me because I'm getting, like, a really weird vibe.",
"Is Lippman getting rid of me? You can tell me.",
"I won't say anything.",
"I don't know anything.",
"You don't know.",
"You see, I don't know anything means there's something to know.",
"lf you really didn't, you'd say: You're crazy.",
" Oh, hi, Mr.",
"Lippman.",
"Elaine.",
"I was wondering if you got a chance to look at that biography of Columbus I gave you.",
"Yes, I did.",
"Yes, I did.",
"Marie, this water is still too cold.",
"Oh, yeah.",
"It's freezing.",
"Hurts your teeth.",
"I'm telling you, something is going on.",
"He never likes anything I recommend, and then that lunch thing.",
"So they forgot to get your lunch.",
"Big deal.",
"What do you know? You've never worked in an office.",
"See, you've worked in an office, George.",
"You understand.",
"Jerry thinks I'm overreacting, but you understand lunch.",
"I don't understand lunch.",
"I don't know anything about it.",
"Just because I got the guy fired doesn't mean I turned him into a bum, does it? What did he do? He purposely mispronounced my name.",
"Instead of saying Costanza he'd say, Can't stand you.",
"Can't stand you.",
" Remember, he made me smell my own gym socks once? I remember he made you wear a jock on your head for a whole class.",
"And the straps were hanging down.",
"Okay, okay.",
"You never even had him for gym.",
"I had him for hygiene.",
"Remember his teeth? It was like from an exhumed corpse.",
"Little baked beans.",
"Come on, tell me what happened.",
"Well, okay.",
"As I said, the guy had it in for me.",
"He actually failed me in gym.",
"Me.",
"And those spastic Schnitzer twins.",
"Can't stand you! Yes, Mr.",
"Heyman? Your underwear was sticking out of your shorts during gym class.",
"Well, that's because I wear boxer shorts.",
"Boxer shorts, huh? What brand? I'm not really sure.",
"l Yeah, well, let's take a look! He gave me a wedgie.",
"And he got fired the next day.",
"Why do they call it a wedgie? Because the underwear is pulled up from the back until it wedges in.",
"They also have an atomic wedgie.",
"Now, the goal there is to actually get the waistband on top of the head.",
"It's very rare.",
"Boys are sick.",
"Well, what do girls do? We just tease someone till they develop an eating disorder.",
"I gotta go back to the library and talk to him.",
"I gotta find out if I'm the guy that ruined his life.",
"Hey, babaloo, you better get home.",
"This guy Bookman from the library, he's waiting for you.",
"What's amazing about the library is here's a place where you can go in take out any book you want.",
"They just give it to you and say, Bring it back when you're done.",
" Reminds you of that pathetic friend everybody had as a kid that would let you borrow any of his stuff if you would just be his friend.",
"That's what the library is.",
"It's a governmentfunded pathetic friend.",
"That's why everybody bullies the library.",
"I'll bring it back on time, I'll bring it back late.",
"What are you gonna do, charge me a nickel? I'm glad you're here so we can straighten this out.",
"Cup of tea? Got any coffee? Coffee? Yeah, coffee.",
"No, I don't drink coffee.",
"You don't? How about instant coffee? No, I don't No instant coffee? Well, I don't Who doesn't have instant coffee? I don't.",
"Buy a jar of Folgers crystals, put it in the cupboard, you forget about it.",
"When you need it, it's there.",
"It lasts forever.",
"It's freezedried.",
"Freezedried crystals.",
"Really? I'll have to remember that.",
"You took this book out in 1 9 7 1 .",
"Yes, and I returned it in 1 9 7 1 .",
"Yeah, '7 1 , that was my first year on the job.",
"Bad year for libraries.",
"Bad year for America.",
"Hippies burning library cards.",
"Abbie Hoffman telling everybody to steal books.",
"I don't judge a man by hair length or musical taste.",
"Rock was never my bag.",
"But you put on a pair of shoes in the New York Public Library, fella.",
"Look, Mr.",
"Bookman I returned that book.",
"I remember it very specifically.",
"You're a comedian.",
"You make people laugh.",
"I try.",
"You think this is all a big joke? No, I don't.",
"I saw you on TV once.",
"I remembered your name from my list.",
"I looked it up.",
"Sure enough, it checked out.",
"You think because you're a celebrity, somehow the law doesn't apply? You're above the law? Certainly not.",
"Well, let me tell you something, funny boy.",
"You know that little stamp, the one that says New York Public Library? That may not mean anything to you.",
"But that means a lot to me.",
"One whole hell of a lot.",
"Sure, go ahead.",
"Laugh if you want to.",
"I've seen your type before.",
"Flashy, making a scene, flaunting convention.",
"Yeah, I know what you're thinking: Why's this guy making such a stink about old library books? Well, let me give you a hint, junior.",
"Maybe we can live without libraries, people like you and me.",
"Maybe.",
"Sure, we're too old to change the world.",
"But what about that kid sitting down opening a book right now in a branch at the local library and finding drawings of peepees and weewees in The Cat in the Hat and The Five Chinese Brothers? Doesn't he deserve better? Look, if you think this is about overdue fines and missing books you better think again.",
"This is about that kid's right to read a book without getting his mind warped.",
"Or maybe that turns you on, Seinfeld.",
"Maybe that's how you get your kicks, you and your goodtime buddies.",
"Well, I got a flash for you, joyboy: Party time is over.",
"You got seven days, Seinfeld.",
"That is one week.",
"What's wrong? It's Bookman, the library cop.",
"So? I didn't do anything wrong.",
"I'm supposed to be at work.",
"I could get fired.",
"I never should've come here.",
"Why don't you leave? I can't.",
"There's no way I'm paying that! I returned that book in 1 9 7 1 ! I have a witness.",
"Sherry Becker.",
"She wore an orange dress.",
"She gave me a piece of Black Jack gum.",
"I said, Licorice gum.",
"What will they think of next? I remember it! Becker, Becker.",
"Kevin went to a public school.",
"He's the 1 4 year old.",
"We were gonna send Marsha to a private school because in some ways, they don't learn enough, I think.",
"So, Sherry, what do you remember about that day at the library? I remember it like it was yesterday.",
"It was a Friday afternoon.",
"I wore a purple dress.",
"Purple? You sure it wasn't orange? Positive.",
"And I was chewing Dentyne.",
"I always chewed Dentyne.",
"Remember, Jerry? Dentyne? No Black Jack? Licorice gum? Never.",
"What else? We were reading passages to each other from that Henry Miller book you had.",
"Tropic of Cancer.",
"No.",
"Tropic of Capricorn.",
"Tropic of Capricorn? Remember? What holds the world together as I have learned from bitter experience is sexual intercourse.",
" Wait a second, wait a second.",
"You're right.",
"I had both of them.",
"We read from Tropic of Capricorn.",
"I was all set to return Tropic of Cancer.",
"And then.",
"George, here's the book.",
"Oh, man.",
"Don't let anybody see it.",
"Don't let anything happen to it.",
"Jerry, it's me, George.",
"Don't worry.",
"I'll return it tomorrow.",
"All right.",
"I'll see you after school.",
"I'm late for Heyman's hygiene.",
"Where are you going? It was nice seeing you again.",
"I just remembered something.",
"I've gotta go.",
"It was George! Read another poem.",
"Pressed chest Fleshed out west Might be the savior Or a garden pest That is great poetry.",
"You should be published.",
"It's great.",
"Well, the library's kind of a cool place when it's closed.",
"Oh, yeah.",
"You don't have to be quiet.",
"Listen to the echo.",
"Hello! Hello! Hello! Hello! Hello! Hello.",
"Mr.",
"Bookman.",
"I remember when the librarian was a much older woman.",
"Kindly, discreet, unattractive.",
"We didn't know anything about her private life.",
"We didn't wanna know about her private life.",
"She didn't have a private life.",
"When you think about that, think about this: The library closes at 5:00, no exceptions.",
"This is your final warning.",
"Got that, kewpie doll? Lippman wants to see me in his office.",
"See me.",
"That can't be good.",
"Maybe you're getting a raise.",
"Maybe I'm getting a wedgie.",
"What? It's George.",
"George is on his way up.",
"Wait till I tell him about the book.",
"Are you okay? What? It's It's Marion's poetry.",
"I can't take it! Oh, Kramer.",
"Remember that biography I recommended? My boss hated it! I'm right here.",
"Oh, sorry.",
"Remember that Columbus book? Columbus.",
"Eurotrash.",
"Well, it's definitely him.",
"Him? Him who? Him who? Heyman him.",
"Heyman, the gym teacher? You found him? Oh, I found him.",
"He was sitting on the steps of the library.",
"I sat down next to him.",
"He smelled like the locker room after that game against Erasmus.",
"That was double overtime.",
"I said, Mr.",
"Heyman it's me, George Costanza.",
"JFK, '7 1 .",
" He doesn't move.",
"So I said: Can't stand you.",
"Can't stand you.",
" He turns and smiles.",
"The little bakedbean teeth.",
"I get up to run away but something was holding me back.",
"It was Heyman.",
"He had my underwear.",
"Here I was on the steps of the 42nd Street library a grown man getting a wedgie.",
"At least it wasn't atomic.",
"It was.",
"So, Georgie boy, guess what happened to Tropic of Cancer.",
"How should I know? Because I gave it to you.",
"Me? Yeah, think.",
"Don't you remember? You kept begging me to see it.",
"Then finally, I agreed.",
"You were supposed to return it.",
"I met you in the gym locker room and gave it to you.",
"The locker room.",
"George, here's the book.",
"Oh, man.",
"Don't let anybody see it.",
"Don't let anything happen to it.",
"It's me, George.",
"Don't worry.",
"I'll return it tomorrow.",
"All right.",
"I'll see you after school.",
"I'm late for Heyman's hygiene.",
"Can't stand you! Yes, Mr.",
"Heyman? Your underwear was sticking out of your shorts during gym class.",
"That's because I wear boxer shorts.",
"Boxer shorts, huh? What brand? I'm not really sure.",
"Yeah, well, let's take a look! Anyway, I hope there's no hard feelings.",
"Hard feelings? What do you know about hard feelings? Ever have a man die in your arms? Ever kill somebody? What is your problem? What's my problem? Punks like you.",
"That's my problem.",
"You better not screw up again, Seinfeld.",
"Because if you do, I'll be all over you like a pit bull on a poodle.",
"That is one tough monkey.",
"So you were saying? So I took your suggestion and I gave my boss Marion's poems the ones that affected Kramer so much.",
"Oh, beautiful.",
"Did he like them? No, he didn't.",
"No, he didn't.",
"Was he out there? No, he's gone.",
"I wonder what happened to him.",
"I guess we'll never know.",
"Can't stand you.",
"Can't stand you.",
"Can't stand you.",
"Can't stand you.",
"Any day that you had gym was a weird school day.",
"You know what I mean? It started off kind of normal.",
"You have, like, English, geometry, social studies and then suddenly, you're, like, in Lord of the Flies for 40 minutes.",
"You're hanging from a rope.",
"You have hardly any clothes on.",
"Teachers are yelling at you, Where's your jockstrap? You know.",
"Kids are throwing dodge balls at you.",
"You're trying to survive.",
"Then it's history science, language.",
"There's something off in the whole flow of that day."]