module.exports = ["It's hard to find a store in a mall.",
"They have a directory but the problem with it is, even if you figure out where you are and where you wanna go you still don't really know, sometimes, which way to walk because it's an upright map.",
"lf you had, like, suctioncup feet, then you could just walk right up on it.",
"Then you could tell, you could be on it going, All right, I'm here.",
"I wanna go to the Gap.",
"That's down there.",
"All right, I'll just walk that way.",
" But people would know.",
"They would see you walking down the mall going: They'd go, That's one of those suctioncup guys.",
"I heard about that guy.",
"He's never lost.",
"One left.",
"What a joke.",
"You can have this one.",
"That's not enough BTUs for my living room.",
"This was a waste of time.",
"I didn't get one either.",
"Why do I always have the feeling everybody's doing something better than me on Saturdays? This is what people do.",
"No, they don't.",
"They're out on some big picnic, they're cooking burgers making out on blankets.",
"They're not at some mall in Jersey watching their friends trying to find the world's cheapest air conditioner.",
"You should see what my father used to do before he bought a new car.",
"He'd go from state to state.",
"He was away for weeks at a time.",
"Like he's running for president and going through the primaries.",
"We'd get phone calls from New Hampshire.",
"We took a little ride, what's the big deal? At least you accomplished something.",
"You got fish.",
"Oh, big accomplishment.",
"Fish.",
"What do they do? What do you do? Hey, this way! Jerry, what time do you have? I have 5:00.",
"Always late.",
"Always late.",
"You're not late.",
"I told them to meet me in front of my building at 6:1 5.",
"Who? My parents.",
"It's their anniversary.",
"I'm taking them out to dinner and a show tonight.",
"Think we'll hit traffic? Of course.",
"It's rush hour.",
"Isn't it the other way? There's no other way.",
"Everybody goes every way all the time.",
"But it's Saturday.",
"You got the picnic and burger traffic.",
"There's picnic traffic? As my grandfather used to say: Sometimes even a picnic's no picnic.",
" I always get myself in this position.",
"Can't be on time.",
"Gotta rush.",
"What's the matter? I have to go to the bathroom.",
"Why do they hide the bathrooms in these malls? You want me to help you with that? No, I got it.",
"What do you think, Georgie boy? Did I need that pointed out for me? What is that gonna do for me? How does that help me, to see her? I'm trying to live my life.",
"Don't show me that.",
"Well, if you like her, go and talk to her.",
"Yeah, women love to get approached in parking garages.",
"I'll go up and say, Hi, how you doing? Would you like a glass of white wine? You get within 1 5 feet, she'd have her finger on the Mace button.",
"That was a guy.",
"That was a guy? Where's the car? Well, I thought it was here.",
"You don't know where we parked? Oh, this is great.",
"Look, I thought it was Green 22.",
"I remember Orange.",
"I thought it was Orange.",
"I didn't pay attention.",
"This is just what I need.",
"I'm sure it's right around here.",
"Yeah, it looks familiar.",
"I remember the elevator.",
"There's elevators all over! Everything looks the same! We're like rats in some experiment.",
"It's over there.",
"I know where it is.",
"It's black, right? Well, it's dark brown.",
"In a parking lot, you write it down.",
"How hard is that? There it is.",
"No, no.",
"That's a Toyota.",
"I thought it was.",
"Hey, didn't we come in over there? I thought we came in over there.",
"How long can fish live in one of these plastic bags? I don't know.",
"Maybe two hours.",
"You better find this car.",
"Let's try this way.",
"I really have to go to the bathroom.",
"Why don't you just go behind one of these cars.",
"Why? There's nobody around.",
"I'll wait.",
"You hold it in like that, you can cause a lot of damage to your bladder.",
"That's what happens to truck drivers.",
"They hold it in all the time and eventually it starts to come out involuntarily.",
"All right.",
"Jerry, are you aware that adult diapers are a $600millionayear industry? Maybe I should just go any time I get the urge, like you, wherever I am.",
"There's too much urinary freedom in this society.",
"I'm proud to hold it in.",
"It builds character.",
"Is that it? No.",
"Hey! Watch it! Maniac.",
"You sure you don't want help with that? I'm gonna put it down behind that car.",
"Worried somebody's gonna pee on it? It's Purple 23.",
"Remember that.",
"Oh, I got it.",
"That I'm supposed to remember.",
"Where the car is, that's insignificant.",
"I think they're laboring.",
"Look at this place! It's huge! All right, let me say this to you: lf I am not in front of my building at 6:1 5, when my parents get there they're gonna put me on an aggravation installment plan that will compound, with interest, for decades.",
"Parents never forget a foulup.",
"I once left my jacket on a bus when I was 1 4.",
"I was flying to Chicago, last week, on a plane: Make sure you hang on to your jacket.",
" There's no way you can call them? Yeah, I'll call them on their car phone.",
"What would it take for his parents to get a car phone? Hypnosis by aliens.",
"Where the hell is this car, Kramer? We need a system.",
"Well, it's gotta be here.",
"Why are they using so many colors? The numbers go up to 40.",
"Maybe it's not on this level.",
"What? There's four different levels.",
"Maybe we're on the wrong level.",
"How long was the escalator ride up? It felt like a couple of levels.",
"You should always bring a pad and a pen.",
"I can't carry a pen.",
"I'm afraid I'll puncture my scrotum.",
"I got a pen.",
"Where is the bathroom in this mall? There's 600 stores, I didn't see one bathroom.",
"What is this, like, a joke? Don't they consult with a urologist when they build one of these places? What's with you? My ear itches.",
"Don't you dare talk to me like that, you hear me? I told you, I don't care! You'll have to wait! Hey, hey, is that really necessary? Why don't you mind your own business.",
"Well, I think hitting a defenseless child is my business.",
"You're ugly.",
"What? You're ugly.",
"You are.",
"You are.",
"That's what you think.",
"That's what I know.",
"I found it! He's got it! No, no, no.",
"All right, that's it.",
"From now on, no more calling out I found it unless we're sitting in it.",
"Jerry, look at my fish.",
"His eyes look a little cloudy.",
"See? Oh, those are your eyes.",
"Oh, they are gonna be furious.",
"Who's got the tickets? I do.",
"I thought you knew this mall.",
"You said you'd been here.",
"It was easy last time.",
"Okay, my fish are dying right in front of me.",
"We've gotta get someone to drive us around to us help look for the car.",
"No one's gonna do that.",
"Excuse me.",
"Hi.",
"We can't seem to find our car.",
"I was wondering if it would be possible to drive us around the garage for five minutes so we can look.",
"Sorry.",
"Just five minutes.",
"Can't do it.",
"We're not skinheads.",
"Excuse me.",
"I can't seem to find my car.",
"Do you think you could drive me? Oh, that's funny? Is that funny? Hey, tell me if you think this is funny: These fish are dying.",
"In an hour they'll be bellyup! Excuse me.",
"Excuse me.",
"Hey, sorry to have disturbed you.",
"Terribly sorry.",
"But the fish will be dead! You do know that? They can't live in plastic.",
"That's not me talking, that's science! It's amazing how shopping makes me have to go.",
"How does my bladder know I'm in a department store? Why don't you just go.",
"No, I can't.",
"Don't you get tired of following rules? You think I'm too cautious? Why be uncomfortable if you don't have to? It's organic.",
"Organic.",
"So is Buddy Hackett.",
"Buddy Hackett? He's a comedian.",
"I know.",
"All right, all right.",
"Hey, you can go over here.",
"I can manage.",
"George! Okay, let's go.",
"But Come on.",
"Kramer.",
"I'm telling you, I've had this condition since I was 11 years old.",
"I've been in and out of hospitals my whole life.",
"I have no control over it.",
"Doctors have told me that when I feel it the best thing to do is just release it.",
"Otherwise I could die.",
"Do you hear what I'm saying to you? I'm telling you that if I don't go, I could die.",
"Die! Is it worth dying for? That's up to you.",
"Oh, so you don't care if I die.",
"What I care about is the sanitary condition of the parking facility.",
"Why would I do it unless I was in mortal danger? I know it's against the law.",
"I don't know.",
"Because I could get uromysitisis poisoning and die, that's why.",
"You think I enjoy living like this? The shame? The humiliation? You know, I've been issued a public urination pass by the city because of my condition.",
"Unfortunately, my little brother ran out of the house with it this morning.",
"Him and his friends are probably peeing all over the place.",
"Jerry! Jerry! Unbelievable.",
"I'm never gonna get out of here.",
"Guy goes to pee, he never comes back.",
"It's like a sciencefiction story.",
"Maybe he went to one of the other levels.",
"I'm gonna look for him.",
"Now you're gonna go? Be back in five minutes.",
"lf you go now we'll find the car, Jerry will show up and we'll never find you! I'll be right back.",
"What's the difference? We'll all be dead eventually.",
"Does that bother you? Yeah, it bothers me.",
"Doesn't it bother you? Not at all.",
"Now, that bothers me even more than dying bothers me.",
"Because people like you live to be 1 20 because you're not bothered by it.",
"How can it not bother you? Well, I once saw this thing on TV with people who are terminally ill.",
"Every one of them believed that the secret of life is just to live every moment.",
"Yeah, I've heard that.",
"Meanwhile, I'm here with you in a parking garage in Jersey.",
"That's a nice jacket.",
"Where'd you get that? Some guy left it over at my mother's house.",
"First of all, you don't even know, technically, that I went.",
"That's for starters.",
"I mean, I could have been pouring a bottle of water out there.",
"I know what you did.",
"Oh, really? Do you? Well it just so happens that I did pour water out.",
"I had a bottle of very tepid water and I poured it out.",
"I could see how you made a mistake because pouring water out sounds very much like a person urinating.",
"And, you know, when you think about it it's really quite an amusing case of mistaken identity.",
"And that's all it is.",
"And now he's gone.",
"I'm sure he's looking for the car.",
"Five minutes, that's all.",
"I just wanna find him.",
"I can't do it.",
"But why? Why can't you do it? I can't.",
"That's not a reason, You can't.",
" You just don't want to.",
"That's right.",
"But why? Why don't you want to? I don't know.",
"Well, wouldn't you get any satisfaction out of helping someone out? No, I wouldn't.",
"All right.",
"All right.",
"l.",
"I want to apologize.",
"I was frightened.",
"I said crazy things, I obviously offended you I insulted your intelligence.",
"The uromysitisis, the water bottle I made all that up.",
"And now I'm gonna tell you the truth.",
"Today my parents are celebrating their 50th Well, I'm jumping ahead here.",
"Their 4 7th wedding anniversary.",
"And we made plans to spend the evening together.",
"They're meeting me in front of my building at 6:1 5.",
"What I haven't told you or anyone else, for that matter is that my father's been in a Red Chinese prison for the past 1 4 years.",
"I mean, the guy had a fat fetish.",
"The inspector never dated a woman under 250 pounds.",
"Really.",
"What did he do with all that fat? Does he just jump up and down on it? Or does he gouge it like Killer Kowalski? Who's Killer Kowalski? He was a wrestler.",
"He would get down on his knees and he'd grab ahold of someone's stomach and squeeze it till they gave.",
"Hey, hey, hey.",
"I have to go to the bathroom.",
"Why don't you just go.",
"What, here? You and Jerry.",
"It's.",
"Okay.",
"All right, I'm gonna go down this row.",
"What? What did I do? I didn't do anything.",
"Kramer! Kramer! What? Don't you believe me? It's their 4 7th anniversary.",
"You know, this is gonna kill them.",
"You're aware of that? Kill them.",
"On the biggest night of their life.",
"Your folks have an anniversary today too? Was your father also in a Red Chinese prison? Red Chinese prison? George! George! Jerry! Jerry! You know when you're walking with someone and you assume that they know where the car is? And you're fine until you see them do this move.",
"Once they do this: When they look back from where they came from.",
"No, you're in bad shape now.",
"Nobody that knows where they're going does that.",
"Pilots on planes don't open the cockpit door and go: Well, what happened was my father was staying with one of China's great military leaders General Chang, who, by the way, came up with the recipe for General Chang's chicken.",
"The one with red pepper and orange peel at Szechwan Gardens? I eat it all the time.",
"Spicy.",
"Apparently, General Chang is a flamboyant man.",
"Complete failure as a general, but a hell of a cook.",
"Look at this.",
"Look at this.",
"Will you look at this? He doesn't have enough with the Mercedes, he has to have two spaces.",
"I tell you, you know what I'd like to do? I'd like to spit on it.",
"I would like to see that.",
"Should l? Should I do it? Teach him a lesson he'll never forget.",
"Who does he think he is? Someone's gotta stop him.",
"It's against the law, isn't it? Well, it certainly should be.",
"Okay.",
"This is some machine.",
"Leave it to the Germans.",
"Let me ask you something.",
"What do they get for a tuneup on this? Jerry! Elaine! Where have you been? I was arrested for urinating.",
"Me too.",
"You what? I have uromysitisis.",
"It's very serious, you know.",
"Jerry, look at my fish.",
"Is he? No, but he's not looking good.",
"Please.",
"We can't find our car.",
"Please, just drive us around the parking lot to find our car.",
"My fish are dying.",
"Sorry.",
"Can't do it.",
"I can see not caring what happens to us.",
"We're human.",
"But what about the fish? The fish? Sorry.",
"That's right, go.",
"Go home to your dumbbells.",
"Go work on your pecs and your lats.",
"We're all really impressed.",
"Yeah, that's right.",
"You heard me.",
"You got a problem with that? Elaine, shut up.",
"Don't worry, I'm packing heat.",
"Hey, hey.",
"Where's Kramer? I don't know.",
"I thought he was with you.",
"Oh, see? See? I knew this was gonna happen.",
"Look at the time.",
"All right, that's it.",
"Did we look over there? We check that side? We came in over there.",
"We didn't come in over there.",
"Where's Kramer? Look at these cars they all look exactly alike.",
"The fumes.",
"I can't breathe.",
"I'm having trouble breathing.",
"Hey, George, there she is again.",
"What are you doing? You're killing me.",
"Ask her to drive us around.",
"There's your opening.",
"That is an opening.",
"Excuse me.",
"I'm really.",
"See, what happened my friend forgot where he parked.",
"Sure, I'll drive you around.",
"You will? Sure.",
"Thank you.",
"Thank you.",
"We're late and my parents are waiting for me and we're stuck here.",
"Well, I wouldn't wanna get lost in here.",
"It smells like a toilet.",
"People are such animals.",
"You're telling me.",
"Filthy pigs.",
"It's a brown Ford.",
"This has happened to me too.",
"It's very frustrating.",
"I've asked several people.",
"They wouldn't even answer me.",
"I'm happy to do it.",
"I'm Michele.",
"Hi, Michele.",
"I'm George.",
"Get out! But I didn't mean anything by it.",
"I don't even know L.",
"Ron Hubbard.",
"I didn't know you were with that group.",
"What about my fish? Boy, those Scientologists, they can be pretty sensitive.",
"I'll say.",
"What is it? The car! The car! The car! The car! I can't believe it! Kramer.",
"Kramer's not here.",
"I knew it.",
"I knew it.",
"I knew this would happen.",
"Kramer! Kramer! Kramer! Kramer! Hey, look.",
"Boy, I had a hell of a time finding that air conditioner.",
"You know I looked everywhere? I completely forgot where I hid it.",
"You know where it was? Purple 23.",
"Right.",
"Purple 23.",
"I could have used you.",
"Sometimes it's good to write those things down.",
"Oh, boy.",
"What time is it? Well, at least there'll be no traffic.",
"Right.",
"Oh, boy.",
"What time does that play start? 8:00.",
"Well, that could be a problem.",
"Where's your little bag of.",
"All right, let's giddyup.",
"See, the problem with the mall garage is that everything looks the same.",
"They try to differentiate it.",
"They put up different colors, different numbers, different letters.",
"What they need to do is name the levels like: Your mother's a whore.",
" You know what I mean? You would remember that.",
"You'd go, I know, I'm parked at 'My father's an abusive alcoholic.",
"I know where I parked."]