module.exports = ["I have never seen an old person in a new bathing suit in my life.",
"I don't know where they get their bathing suits.",
"But my father has bathing suits from other centuries.",
"My parents live in Florida.",
"And if you go down there and you forget your bathing suit then they want you to wear one of theirs.",
"You know how that gets? You need trunks, son? I got trunks for you.",
"You can wear my trunks.",
" Fathers don't wear bathing suits, they wear trunks.",
"It's kind of the same thing a tree would wear if it went swimming.",
"So I get in the water in this thing, and it's, like, floating around me somewhere.",
"You ever put on a bathing suit that you don't know exactly where you are inside the bathing suit? You bump into somebody, No, I'm parasailing.",
"I'm waiting for the boat to come back.",
" It was supposed to be here at 7:30.",
"Call the airlines again.",
"What happened to the Scotch tape? Who takes the Scotch tape? Nobody returns anything around here.",
"Oh, I think that's them.",
"Know what I'll do next time? I'll hide it so nobody can find it.",
"Hi! Welcome! Hi! Welcome.",
"How are you? Welcome to Florida! Hi, Mr.",
"Seinfeld.",
"Hey, there's the old man.",
"So, what took you so long? We waited 35 minutes in the rentacar place.",
"I don't know why.",
"We would have picked you up.",
"What's the difference? You could use our car.",
"I don't want to use your car.",
"What's wrong with our car? Nothing.",
"It's fine.",
"What if you want to use it? We don't.",
"What? We use it.",
"lf you were using it, we wouldn't.",
"So, what, you'd hitch? How much is a rentacar? I don't know, 25 bucks a day.",
"What? Oh, you're crazy.",
"Plus the insurance.",
"Oh, I didn't get the insurance.",
"How could you not get the insurance? We'll pay for the car.",
"You're not paying for it.",
"Morty.",
"God, it's so hot in here.",
"Why don't you put on the air conditioning? You don't need the air conditioner.",
"Do you have your speech all ready? Do I have to make a speech? Of course.",
"They're giving a testimonial for your father.",
"You could do your comic routines.",
"Oh, yeah.",
"That'll go over real well with that crowd.",
"You have a lake.",
"The lake isn't real.",
"The lake is real.",
"Are you kidding? They built the lake.",
"But it's real, it's water.",
"Where are you going with those? I'll put Elaine's stuff in here.",
"Don't sleep in there.",
"Sleep in the bedroom.",
"I can't take your bedroom.",
"I'm up at 6:00 in the morning.",
"I can't kick you out of your bed.",
"We don't even sleep.",
"Ma.",
"It's a sofa bed.",
"You'll be uncomfortable.",
"What about you? Why should I be comfortable? What about him? Don't worry.",
"He's comfortable.",
"I'll sleep standing up.",
"I'll be fine.",
"Will you stop? Yeah, I'll just stay in here.",
"Jerry.",
"Jerry, you don't have to stay on the couch on my account.",
"You two can stay in there together.",
"That's not a good idea.",
"I thought that you Not now.",
"She's right inside.",
"What happened? I don't know.",
"We decided we don't really work as a couple.",
"What does that mean? Well Why are you whispering? Nothing, nothing.",
"Elaine.",
"What about her? Would you please be? You know, look at the sundried tomatoes.",
"Where were they five years ago? It just goes to show you, you never know what What, you know, could happen to a vegetable.",
"It could just take right off at any time.",
"We've tried all kinds of arrangements but we can't seem to be friends when we sleep together.",
"Why do you need more friends? You've got plenty of friends.",
"He's an idealist.",
"What are you looking for? I'm looking.",
"I like looking.",
"He likes looking.",
"So look.",
"But how long can you look? I'm going for the record.",
"Your father wouldn't say so, but he's really glad you came.",
"Oh, come on.",
"This is a big thing for him.",
"Outgoing president of the condo association.",
"So they arrived safely.",
"Remember Jack and Doris? Nice to see you.",
"This is Elaine.",
"Hi.",
"Nice to meet you.",
"Hello.",
"Hello.",
"Pleased to meet you.",
"Hey, Jerry you came all the way down here for this? And scuba diving.",
"Scuba diving? Who's going scuba diving? We're going.",
"We'll be back in time.",
"What do you have to go scuba diving for? For fun.",
"For fun? Jack, have some sponge cake.",
"No.",
"Thanks, no.",
"Jack is emceeing tomorrow.",
"He's in charge of the whole thing.",
"So, Jerry, your mother tells me you're gonna do one of your little comedy skits tomorrow.",
"I don't think so.",
"No? Listen, Morty, you want to settle up for last night? All right.",
"I owe you $ 1 9.",
"45.",
"What did you have? You had the minute steak.",
"Yeah.",
"Did you have a Coke or what? I did not have a Coke.",
"Somebody had a Coke.",
"I had a Coke.",
"Oh, and I had the scampi.",
"So, that's $ 1 7.",
"1 0, and the tax and the tip.",
"All right, make it 20 bucks.",
"It's $ 1 9.",
"45, Morty.",
"$ 1 9.",
"45? See, you know your father.",
"You got to get it right to the penny.",
"But that's why he was such a good president.",
"Hey, what kind of pen is that? This pen? Yeah.",
"Oh, this is an astronaut pen.",
"It writes upside down.",
"They use this in space.",
"Oh, that's the astronaut pen.",
"I heard about that.",
"Where did you get it? It was a gift.",
"Because a lot of times I write in bed and I have to turn and lean on my elbow to make the pen work.",
"Take the pen.",
"Oh, no.",
"Go ahead.",
" I couldn't.",
"Take it.",
"I can't take it.",
"Do me a personal favor.",
"No, I'm not comfortable.",
"I cannot take it.",
"Take the pen.",
"Are you sure? I'm positive.",
"Take the pen.",
"Okay, thank you very much.",
"Thank you.",
"Gee, boy.",
"Jack, what are you doing? Stop it.",
"Jack, we should go.",
"It was nice meeting you.",
"Nice to meet you.",
"Thanks again.",
"Come on! She's adorable.",
"What did you take his pen for? He gave it to me.",
"But you didn't have to take it.",
"She's gotta make a big deal out of everything.",
"He offered it to me.",
"Because you made such a big fuss.",
"Well, I liked it.",
"Should l have said I didn't like it? You shouldn't have said anything.",
"What did you expect? He could have said, Thank you, and put it back in his pocket.",
"He loves that pen.",
"Come on.",
"He talks about it all the time.",
"He goes on and on about how it writes upside down, how astronauts use it.",
"He never should have offered it.",
"He didn't think you'd accept.",
"Well, he was wrong.",
"I know his wife.",
"She has some mouth on her.",
"She'll tell everyone in the condo now that you made him give you the pen.",
"They're talking about it right now.",
"So you want me to return it? Yes.",
"He's not gonna return that pen.",
"That's ridiculous.",
"I don't even want the pen now.",
"Jack can afford to give away a pen with all his money, believe me.",
"He gives me a check for $ 1 9.",
"45.",
"He didn't have a Coke.",
"Here, let me see it.",
"Hey, it writes upside down.",
"Yeah.",
"Come in.",
"You okay in here? Why is it so hot in here? How can they sleep like this? It's only for three days.",
"Today's over.",
"Then we have tomorrow.",
"We leave on Sunday.",
"It's one day, really.",
"What is with this bar? It's right in my back.",
"It's killing me.",
"You wanna switch? I'm on a love seat.",
"I got my feet up in the air like I'm in a space capsule.",
"I am never gonna fall asleep.",
"Oh, no, don't say that.",
"You'll jinx me.",
"How can they not put the air conditioning on? They're nuts with temperature.",
"This bar is right in my back.",
"It's making a dent.",
"How about that guy writing a check for $ 1 9.",
"45? I'm sweating here.",
"I'm in bed, sweating.",
"It's one day.",
"Half a day, really.",
"I mean, you subtract showers and meals, it's like 20 minutes.",
"It'll go by like that.",
"Stay on 95 South to Biscayne Boulevard.",
"Then you make a left turn.",
"Put your blinker on immediately, there's an abutment there.",
"Then you're gonna merge over very quickly, but stay on Biscayne.",
"Don't get off Biscayne, you understand me? Stay on Biscayne.",
"You're going underwater? Yes, generally, that's where scuba diving is done.",
"What do you have to go for? What's down there that's so special? What's so special up here? What's the matter? My back.",
"What happened? That That bed.",
"The bar was right in my back.",
"I told you to let us sleep in there.",
"Then you would be hunched over.",
"I don't even know if I can go scuba diving.",
"You can't go? So stay home.",
"You can go.",
"Without you? That's the reason you came down.",
"Don't go.",
"You sure? Maybe you should see a doctor.",
"We'll stay in a hotel tonight.",
"No, we'll stay in there.",
"Why don't you get a new sofa? Nobody uses it.",
"I'm buying you a new sofa.",
"Jerry, don't talk crazy.",
"Mrs.",
"Seinfeld, please I am begging you: Put the air conditioner on.",
"You're hot? I've lost six pounds.",
"I don't even know how to work it.",
"I keep telling her it's like an oven in here.",
"Is everybody up? Hi, how are you? Hello, Jerry.",
"Evelyn, this is Elaine.",
"Hi, Evelyn.",
"Jerry, you got thin.",
"Too thin? Oh, stop worrying so much about how you look.",
"So where's the new pen? What? The pen.",
"The one Jack Klompus gave you.",
"How did you know that? Blanche told me.",
"Blanche? That's some good pen.",
"Writes upside down.",
"Yeah.",
"The astronauts use them.",
"What did Blanche say? I don't know, she said Jerry wanted the pen.",
"I never really wanted the pen.",
"He gave him the pen.",
"Morty.",
"Why? You don't like the pen? No, no, l Because if you don't, give it back to him.",
"Is that what she said? Who? Blanche.",
"What are you talking about? Hello? Oh, hello, Gussy.",
"What? Jerry wouldn't do that.",
"Jack gave it to him.",
"All he said was he liked it.",
"I mean, nobody put a gun to his head.",
"You're giving him back that pen.",
"Somebody, please.",
"The air conditioner.",
"Oh, my God, I forgot all about it.",
"All I said was, I like the pen.",
" How the hell do you work this thing? Maybe you shouldn't go tonight.",
"Oh, no, no, I wanna go.",
"But your back hurts.",
"Maybe a couple of muscle relaxers would help.",
"Oh, okay.",
"You can turn down the air conditioning if you want.",
"No, I'm fine.",
"You're not too cold? No.",
"Don't be alarmed.",
"Oh, my God.",
"What the hell happened to you? I'm okay.",
"My capillaries burst.",
"Your capillaries? Do you know what you look like? How you doing? Having a good time.",
"Is it my imagination or is it freezing in here? What happened to your eyes? Well, I started to go under With the instructor? Yeah, I got about 1 0 feet down and felt this tremendous pressure on my mask like my eyeballs were being sucked out of their sockets.",
"I told you.",
"Excuse me.",
"Doris would like to borrow your red pocketbook to go with her shoes.",
"The shoes have to match the pocketbook.",
"What's she doing, yoga? My back hurts.",
"Morty, better hurry up.",
"Get ready.",
"We got plenty of time.",
"What happened? I got in a fistfight with one of the ladies at the pool.",
"It's from scuba diving.",
"What's there to see underwater? Listen, Mr.",
"Klompus it was a nice gesture to give me the pen, but I don't really need it.",
"You what? It's a terrific pen but I think you should keep it.",
"Well, I mean Take it.",
"All right.",
"You know, Jack, you got a hell of a nerve taking that kid's pen.",
"Whose pen? His pen.",
"This happens to be my pen.",
"You didn't give it to him? What are you talking about? He practically begged me for it.",
"Where do you come off with this crap? Listen, do you think I take everything everybody offers me? You offered me sponge cake yesterday.",
"Did I take it? You didn't want it.",
"Of course I wanted it! I love sponge cake.",
"Who said you couldn't have it? I mean what the hell do I care whether you have sponge cake? Because I saw the look on your face last week when I took the Scotch tape.",
"So you got the Scotch tape.",
"I've been looking all over for it.",
"I'll give it back.",
"I don't want it.",
"I don't want it! You know, Jack, do me a favor, will you? Take the pen and the Scotch tape and get the hell out of here.",
"Listen, do you think I give a damn? Nerve of that guy, taking back that pen.",
"Well, that's it for them.",
"What is going on in this community? Are you people aware of what's happening? What is driving you to this behavior? Is it the humidity? Is it the Muzak? Is it the white shoes? I have no use for either one of them.",
"I don't want them there tonight.",
"Isn't he supposed to emcee? Yeah, he's supposed to be the emcee.",
"Well, this should be a very interesting evening.",
"What about those muscle relaxers? Say astronaut.",
" Say what? Say what? You took too many of those pills.",
"Astronaut? Say it.",
"Astronaut! Astro.",
"Good.",
"Okay.",
"Last year, I took him to the hospital every day.",
"Did he ever say thank you? Oh, God.",
"Uncle Leo.",
"Hello! Morty, are you nervous? What nervous? What's with the sunglasses? Who are you, Van Johnson? I got a black eye.",
"Hello.",
"Oh, Elaine this is my Aunt Stella.",
"Stella! Stella! Her back hurts.",
"We saw you on The Tonight Show last week.",
"I thought Johnny was very rude to you.",
"He didn't even let you talk.",
"No, no.",
"You need some new material.",
"I've heard you do that dog routine three times already.",
"Stella! Stella! You should get your cousin Jeffrey to write some material for you.",
"What? Jeffrey works for the Parks Department.",
"You should read the letters he's written.",
"He's funnier than the whole bunch of you.",
"Oh, here's Jack.",
"We should sit down.",
"This better be good.",
"I'm missing Golden Girls for this.",
"I hate her like poison.",
"Hey, Jack, let's get started.",
"Ladies and gentlemen, as you know every year, phase two of the Pines of Mar Gables honors the previous year's president.",
"And this year, we are honoring Morty Seinfeld.",
"Morty! A man who slept more hours on the job than Ronald Reagan.",
"Slept on the job? Being president of the condo is not easy.",
"It requires hard work, dedication, and commitment.",
"And unfortunately, he possesses none of these qualities.",
"I wonder what he ever did.",
"He's joking.",
"His administration did excel in one department: The hiring of incompetents.",
"That's what you say.",
"But we do owe him a debt of gratitude because by not fixing the crack in the sidewalk it put Mrs.",
"Ziven out of commission for a few weeks.",
"Tell them about when you took my son's pen back.",
"Tell them about that.",
"Dad.",
"He gave my son a pen, and then he takes it back.",
"Tell them that! I took it back? He gave it to me! That's enough.",
"Sit down.",
"I'm not finished! Give me that microphone.",
"Give it! Morty, give me that.",
"Give him the pen.",
"You broke my dental plate.",
"Doris! He broke my dental plate.",
"You son of a bitch.",
"I'll sue you.",
"Jerry, do your act.",
"I can't.",
"Nobody's even listening.",
"Well, they're all gonna leave.",
"I got witnesses here.",
"Even your wife is on my side.",
"How you folks doing tonight? Hey, have you ever noticed how they give you the peanuts on the planes? Not my Harry! He flies first class! Who thought the thing everybody wants on a plane is a peanut? I'd rather have a bottle of Scotch! Do the dog routine.",
"All I said was, I like the pen! Stella! You could aggravate it.",
"I wouldn't go anywhere for at least five days.",
"Five days? You want me to stay here for five more days? There must be some mistake.",
"I'm afraid not.",
"Five days.",
"Here.",
"So we have you for five more days.",
"There's no point in me staying.",
"You're just gonna be Excuse me? Nothing.",
"Good morning.",
"Hi, Evelyn.",
"Has Morty decided on a lawyer yet? I don't think so.",
"Because my nephew Larry could do it.",
"He's a brilliant lawyer.",
"He says Jack has no case.",
"I'll ask him when he gets up.",
"Oh, and I spoke to Arnold and he says that according to the bylaws of the condo constitution they need six votes to throw you out for unruly behavior.",
"Not five.",
"Dr.",
"Chernov is the one you'll have to suck up to.",
"Oh, my back.",
"Oh, my back.",
"That bar.",
"Who the hell could sleep on that thing? I was very comfortable.",
"Morty Arnold says they need six votes to throw you out.",
"It's in the constitution.",
"Who are you? I'm a chiropractor.",
"What, are you kidding me? Five more days? Well, today's almost over, and weekdays always go by fast.",
"And Friday, we're leaving, so it's like two days, really.",
"It's like a cup of coffee.",
"It'll go by like that.",
"Is Florida not hot and muggy enough for these people? They love heat.",
"lf they ever decide to land men on the sun I think these old retired guys will be the only ones that will be able to handle it.",
"They'll sit there on the redwood benches, washcloth on their head, going: I'm trying to get a sweat going."]